apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dremio-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ required "Ingress Hostname is required" $.Values.ingress.hostname }}
    secretName: {{ required "Ingress Hostname is required" $.Values.ingress.hostname }}
  rules:
  - host: {{ required "Ingress Hostname is required" $.Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dremio-client
            port:
              number: 9047